const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const { formatCurrency } = require('../../utils/helpers');

const uploadDir = process.env.UPLOAD_DIR || './uploads';

const createDir = (dir) => {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
};

const getCompanyHeader = (doc) => {
  doc.fontSize(16).font('Helvetica-Bold').text(process.env.PDF_COMPANY_NAME, 50, 30);
  doc.fontSize(10).font('Helvetica');
  doc.text(process.env.PDF_COMPANY_ADDRESS, 50, 50);
  doc.text(`Phone: ${process.env.PDF_COMPANY_PHONE}`, 50, 65);
  doc.text(`Email: ${process.env.PDF_COMPANY_EMAIL}`, 50, 80);
};

const getDocumentTitle = (doc, title) => {
  doc.fontSize(18).font('Helvetica-Bold').text(title, 50, 120);
};

const getDocumentDetails = (doc, details) => {
  let y = 160;
  doc.fontSize(10).font('Helvetica');

  Object.entries(details).forEach(([key, value]) => {
    doc.text(`${key}: ${value}`, 50, y);
    y += 15;
  });

  return y + 10;
};

const createTable = (doc, columns, rows, startY) => {
  const columnWidth = (doc.page.width - 100) / columns.length;
  let y = startY;
  const lineHeight = 20;

  doc.fontSize(9).font('Helvetica-Bold');
  doc.rect(50, y, doc.page.width - 100, lineHeight).stroke();

  columns.forEach((col, i) => {
    doc.text(col, 50 + (i * columnWidth), y + 5, { width: columnWidth });
  });

  y += lineHeight;
  doc.font('Helvetica').fontSize(9);

  rows.forEach(row => {
    doc.rect(50, y, doc.page.width - 100, lineHeight).stroke();
    row.forEach((cell, i) => {
      doc.text(cell, 50 + (i * columnWidth), y + 5, { width: columnWidth });
    });
    y += lineHeight;
  });

  return y + 10;
};

const addFooter = (doc) => {
  const pageHeight = doc.page.height;
  doc.fontSize(9).font('Helvetica');
  doc.text('This document is generated by Trading ERP System', 50, pageHeight - 50, { align: 'center' });
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, 50, pageHeight - 30, { align: 'center' });
};

/**
 * Phase 4, C16: FW-only internal-record banner.
 *
 * FlorWay PIs / SOs / Invoices are internal records — the factory sends
 * the actual document to the buyer. Banner draws across the top of the
 * page in FW iron-deep to make it unmistakable on print/share.
 *
 * No-op for non-FW brands. Call BEFORE getCompanyHeader so the banner
 * occupies y=0..28 and the header that follows uses the same coordinate
 * system; downstream content offsets ~32px when banner is present.
 *
 * @param {PDFDocument} doc       Active pdfkit doc.
 * @param {object} entity         The PI/SO/Invoice/etc with .brandCode.
 * @returns {number}              y offset added (32 if FW, 0 otherwise).
 */
const addFwInternalRecordBanner = (doc, entity) => {
  if (!entity || entity.brandCode !== 'FW') return 0;
  const FW_IRON_DEEP = '#1F2933';
  const FW_CREAM = '#F1EEE7';
  const pageWidth = doc.page.width;
  doc.save();
  doc.rect(0, 0, pageWidth, 28).fill(FW_IRON_DEEP);
  doc.fillColor(FW_CREAM).font('Helvetica-Bold').fontSize(10)
     .text(
       'FACTORY WILL SEND TO BUYER  -  INTERNAL RECORD',
       0, 9,
       { align: 'center', width: pageWidth, characterSpacing: 1.5 }
     );
  doc.restore();
  doc.y = 32;  // move cursor below banner for downstream content
  return 32;
};


module.exports = {
  PDFDocument, fs, path, formatCurrency, uploadDir,
  createDir, getCompanyHeader, getDocumentTitle, getDocumentDetails,
  createTable, addFooter, addFwInternalRecordBanner,
};