const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const { formatCurrency } = require('../../utils/helpers');

const uploadDir = process.env.UPLOAD_DIR || './uploads';

const createDir = (dir) => {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
};

/**
 * Phase 4.20 (2026-05-18): brand-aware header. When called with a Brand
 * row (resolved via brandSafetyGateway.resolveBrandOrThrow), prints the
 * brand's displayName + sender email + footerLegalText. Falls back to
 * PDF_COMPANY_NAME env vars for legacy callers that don't pass a brand
 * (only SH historical contexts — every new caller should pass brand).
 *
 * Color: primaryColor used for the company-name band so each brand
 * looks visually distinct on print (SH forest #1D5A32, FW iron-deep
 * #1F2933, HH iron-deep). Tokens come from brandStyleTokens.resolveTokens.
 */
const getCompanyHeader = (doc, brand = null) => {
  const tokens = require('./brandStyleTokens');
  const t = brand ? tokens.resolveTokens(brand) : null;

  const companyName = t?.displayName || process.env.PDF_COMPANY_NAME || 'Sovern House';
  const companyAddress = t?.footerLegal || process.env.PDF_COMPANY_ADDRESS || '';
  const companyEmail = t?.senderEmail || process.env.PDF_COMPANY_EMAIL || '';
  const companyPhone = process.env.PDF_COMPANY_PHONE || '';
  const primaryColor = t?.primaryColor || '#0E0D0C';
  const ink = t?.ink || '#0E0D0C';

  doc.save();
  doc.fontSize(16).font('Helvetica-Bold').fillColor(primaryColor).text(companyName, 50, 30);
  doc.fontSize(10).font('Helvetica').fillColor(ink);
  if (companyAddress) doc.text(companyAddress, 50, 50);
  if (companyPhone) doc.text(`Phone: ${companyPhone}`, 50, 65);
  if (companyEmail) doc.text(`Email: ${companyEmail}`, 50, 80);
  doc.restore();
};

const getDocumentTitle = (doc, title) => {
  doc.fontSize(18).font('Helvetica-Bold').text(title, 50, 120);
};

const getDocumentDetails = (doc, details) => {
  let y = 160;
  doc.fontSize(10).font('Helvetica');

  Object.entries(details).forEach(([key, value]) => {
    doc.text(`${key}: ${value}`, 50, y);
    y += 15;
  });

  return y + 10;
};

const createTable = (doc, columns, rows, startY) => {
  const columnWidth = (doc.page.width - 100) / columns.length;
  let y = startY;
  const lineHeight = 20;

  doc.fontSize(9).font('Helvetica-Bold');
  doc.rect(50, y, doc.page.width - 100, lineHeight).stroke();

  columns.forEach((col, i) => {
    doc.text(col, 50 + (i * columnWidth), y + 5, { width: columnWidth });
  });

  y += lineHeight;
  doc.font('Helvetica').fontSize(9);

  rows.forEach(row => {
    doc.rect(50, y, doc.page.width - 100, lineHeight).stroke();
    row.forEach((cell, i) => {
      doc.text(cell, 50 + (i * columnWidth), y + 5, { width: columnWidth });
    });
    y += lineHeight;
  });

  return y + 10;
};

/**
 * Phase 4.20 (2026-05-18): brand-aware footer. When called with a Brand
 * row, prints the brand's footerLegalText and uses the brand's steel
 * color for the meta-line. Legacy callers without a brand fall back to
 * the original "Trading ERP System" line.
 */
const addFooter = (doc, brand = null) => {
  const tokens = require('./brandStyleTokens');
  const t = brand ? tokens.resolveTokens(brand) : null;

  const pageHeight = doc.page.height;
  const steel = t?.steel || '#6B7280';
  const footerLegal = t?.footerLegal || 'This document is generated by Trading ERP System';

  doc.save();
  doc.fontSize(9).font('Helvetica').fillColor(steel);
  doc.text(footerLegal, 50, pageHeight - 50, { align: 'center', width: doc.page.width - 100 });
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, 50, pageHeight - 30, { align: 'center', width: doc.page.width - 100 });
  doc.restore();
};

/**
 * Phase 4, C16: FW-only internal-record banner.
 *
 * FlorWay PIs / SOs / Invoices are internal records — the factory sends
 * the actual document to the buyer. Banner draws across the top of the
 * page in FW iron-deep to make it unmistakable on print/share.
 *
 * No-op for non-FW brands. Call BEFORE getCompanyHeader so the banner
 * occupies y=0..28 and the header that follows uses the same coordinate
 * system; downstream content offsets ~32px when banner is present.
 *
 * @param {PDFDocument} doc       Active pdfkit doc.
 * @param {object} entity         The PI/SO/Invoice/etc with .brandCode.
 * @returns {number}              y offset added (32 if FW, 0 otherwise).
 */
const addFwInternalRecordBanner = (doc, entity) => {
  if (!entity || entity.brandCode !== 'FW') return 0;
  const FW_IRON_DEEP = '#1F2933';
  const FW_CREAM = '#F1EEE7';
  const pageWidth = doc.page.width;
  doc.save();
  doc.rect(0, 0, pageWidth, 28).fill(FW_IRON_DEEP);
  doc.fillColor(FW_CREAM).font('Helvetica-Bold').fontSize(10)
     .text(
       'FACTORY WILL SEND TO BUYER  -  INTERNAL RECORD',
       0, 9,
       { align: 'center', width: pageWidth, characterSpacing: 1.5 }
     );
  doc.restore();
  doc.y = 32;  // move cursor below banner for downstream content
  return 32;
};

/**
 * Phase 4.15a — backward-compatible pipe-to-disk-OR-buffer helper.
 *
 * Existing generators across this folder all follow the same pattern:
 *   1. Build a `doc` (PDFKit).
 *   2. Pipe to a fs.createWriteStream(filepath).
 *   3. doc.end().
 *   4. resolve(filename) when the stream finishes.
 *
 * The MCP layer (Phase 4.15a) wants the bytes in-memory so it can pipe
 * them directly to a Drive upload — disk artifacts there would leak.
 * This helper switches between the two modes based on opts.returnBuffer:
 *
 *   - returnBuffer:false (default): pipe to disk, resolve(filename).
 *     REST callers and existing /api/pdf routes keep working unchanged.
 *   - returnBuffer:true: collect doc 'data' events, resolve(Buffer)
 *     when 'end' fires. No disk write.
 *
 * Call site pattern (replace the inline stream + resolve/reject block):
 *
 *   const sink = pipeToBufferOrDisk(doc, opts, filepath, filename);
 *   // ... build PDF content via doc.text(...), doc.addPage(), etc. ...
 *   doc.end();
 *   return sink;
 *
 * The helper handles all four success/failure paths.
 */
function pipeToBufferOrDisk(doc, opts, filepath, filename) {
  if (opts && opts.returnBuffer) {
    return new Promise((resolve, reject) => {
      const buffers = [];
      doc.on('data', (b) => buffers.push(b));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);
    });
  }
  const stream = fs.createWriteStream(filepath);
  doc.pipe(stream);
  return new Promise((resolve, reject) => {
    stream.on('finish', () => resolve(filename));
    stream.on('error', reject);
    doc.on('error', reject);
  });
}


/**
 * Phase 4.19b/c/d/e + Phase 4.20 (2026-05-18) — brand-safety gateway
 * for the generic PDF renderers in this folder (PI / SO / Invoice /
 * PackingList / PurchaseOrder / Credit Note / Statement / Sales Note).
 *
 * Phase 4.19 refused FW/HH entities outright because `getCompanyHeader`
 * was SH-only. Phase 4.20 made `getCompanyHeader` + `addFooter`
 * brand-aware (they consume a Brand row via brandStyleTokens). The
 * gateway now permits FW/HH as long as a Brand row resolves — and
 * still refuses on missing brandCode, unknown brand, and Resilient
 * items under SH (rule #9 special case).
 *
 * `brandedQuotationRenderer.js` has its own richer gateway for the
 * brand-aware Quotation sub-renderers; this helper is for the OTHER
 * documents (PI/SO/Invoice/etc) that share `getCompanyHeader`.
 *
 * Throws BrandLeakError on any rule #9 violation. Caller surfaces as
 * 422 / clear chatter event.
 *
 * @param {object}  entity    PI/SO/Invoice/etc Sequelize instance or
 *                            plain object. Must have .brandCode + .id.
 * @param {Array}   items     line items (with .product or .Product)
 * @param {string}  docKind   human-readable doc type for the error msg
 *                            ("Proforma Invoice", "Sales Order", etc.)
 */
function assertSalesDocBrandSafe(entity, items, docKind) {
  const { isResilient, BrandLeakError } = require('../brandSafetyGateway');

  if (!entity?.brandCode) {
    throw new BrandLeakError(
      `Refusing to render ${docKind} ${entity?.id || '(unknown id)'}: brandCode is missing on the entity.`,
      { entityId: entity?.id, leakField: 'brandCode' }
    );
  }

  if (!['SH', 'FW', 'HH'].includes(entity.brandCode)) {
    throw new BrandLeakError(
      `Refusing to render ${docKind} ${entity.id}: unknown brandCode "${entity.brandCode}".`,
      { entityId: entity.id, brandCode: entity.brandCode, leakField: 'brandCode' }
    );
  }

  // SH + Resilient items is a hard rule #9 violation. Walk Products.
  if (Array.isArray(items)) {
    const slugs = [];
    for (const it of items) {
      const p = it.Product || it.product;
      if (p?.productType) slugs.push(p.productType);
      if (p?.category?.slug) slugs.push(p.category.slug);
    }
    if (entity.brandCode === 'SH' && isResilient(slugs)) {
      throw new BrandLeakError(
        `Refusing to render ${docKind} ${entity.id}: brand is SH but line items contain ` +
        `Resilient flooring (${slugs.filter(Boolean).join(', ')}). Rule #9 — Resilient is ` +
        `FW or HH, never SH. Correct the entity's brandCode first.`,
        { entityId: entity.id, brandCode: 'SH', leakField: 'items_resilient_under_sh' }
      );
    }
  }
}

module.exports = {
  PDFDocument, fs, path, formatCurrency, uploadDir,
  createDir, getCompanyHeader, getDocumentTitle, getDocumentDetails,
  createTable, addFooter, addFwInternalRecordBanner,
  pipeToBufferOrDisk,
  assertSalesDocBrandSafe,
};