const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const { formatCurrency } = require('../../utils/helpers');

const uploadDir = process.env.UPLOAD_DIR || './uploads';

const createDir = (dir) => {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
};

const getCompanyHeader = (doc) => {
  doc.fontSize(16).font('Helvetica-Bold').text(process.env.PDF_COMPANY_NAME, 50, 30);
  doc.fontSize(10).font('Helvetica');
  doc.text(process.env.PDF_COMPANY_ADDRESS, 50, 50);
  doc.text(`Phone: ${process.env.PDF_COMPANY_PHONE}`, 50, 65);
  doc.text(`Email: ${process.env.PDF_COMPANY_EMAIL}`, 50, 80);
};

const getDocumentTitle = (doc, title) => {
  doc.fontSize(18).font('Helvetica-Bold').text(title, 50, 120);
};

const getDocumentDetails = (doc, details) => {
  let y = 160;
  doc.fontSize(10).font('Helvetica');

  Object.entries(details).forEach(([key, value]) => {
    doc.text(`${key}: ${value}`, 50, y);
    y += 15;
  });

  return y + 10;
};

const createTable = (doc, columns, rows, startY) => {
  const columnWidth = (doc.page.width - 100) / columns.length;
  let y = startY;
  const lineHeight = 20;

  doc.fontSize(9).font('Helvetica-Bold');
  doc.rect(50, y, doc.page.width - 100, lineHeight).stroke();

  columns.forEach((col, i) => {
    doc.text(col, 50 + (i * columnWidth), y + 5, { width: columnWidth });
  });

  y += lineHeight;
  doc.font('Helvetica').fontSize(9);

  rows.forEach(row => {
    doc.rect(50, y, doc.page.width - 100, lineHeight).stroke();
    row.forEach((cell, i) => {
      doc.text(cell, 50 + (i * columnWidth), y + 5, { width: columnWidth });
    });
    y += lineHeight;
  });

  return y + 10;
};

const addFooter = (doc) => {
  const pageHeight = doc.page.height;
  doc.fontSize(9).font('Helvetica');
  doc.text('This document is generated by Trading ERP System', 50, pageHeight - 50, { align: 'center' });
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, 50, pageHeight - 30, { align: 'center' });
};


module.exports = {
  PDFDocument, fs, path, formatCurrency, uploadDir,
  createDir, getCompanyHeader, getDocumentTitle, getDocumentDetails,
  createTable, addFooter,
};