const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const { formatCurrency } = require('../utils/helpers');

const uploadDir = process.env.UPLOAD_DIR || './uploads';

const createDir = (dir) => {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
};

const getCompanyHeader = (doc) => {
  doc.fontSize(16).font('Helvetica-Bold').text(process.env.PDF_COMPANY_NAME, 50, 30);
  doc.fontSize(10).font('Helvetica');
  doc.text(process.env.PDF_COMPANY_ADDRESS, 50, 50);
  doc.text(`Phone: ${process.env.PDF_COMPANY_PHONE}`, 50, 65);
  doc.text(`Email: ${process.env.PDF_COMPANY_EMAIL}`, 50, 80);
};

const getDocumentTitle = (doc, title) => {
  doc.fontSize(18).font('Helvetica-Bold').text(title, 50, 120);
};

const getDocumentDetails = (doc, details) => {
  let y = 160;
  doc.fontSize(10).font('Helvetica');

  Object.entries(details).forEach(([key, value]) => {
    doc.text(`${key}: ${value}`, 50, y);
    y += 15;
  });

  return y + 10;
};

const createTable = (doc, columns, rows, startY) => {
  const columnWidth = (doc.page.width - 100) / columns.length;
  let y = startY;
  const lineHeight = 20;

  doc.fontSize(9).font('Helvetica-Bold');
  doc.rect(50, y, doc.page.width - 100, lineHeight).stroke();

  columns.forEach((col, i) => {
    doc.text(col, 50 + (i * columnWidth), y + 5, { width: columnWidth });
  });

  y += lineHeight;
  doc.font('Helvetica').fontSize(9);

  rows.forEach(row => {
    doc.rect(50, y, doc.page.width - 100, lineHeight).stroke();
    row.forEach((cell, i) => {
      doc.text(cell, 50 + (i * columnWidth), y + 5, { width: columnWidth });
    });
    y += lineHeight;
  });

  return y + 10;
};

const addFooter = (doc) => {
  const pageHeight = doc.page.height;
  doc.fontSize(9).font('Helvetica');
  doc.text('This document is generated by Trading ERP System', 50, pageHeight - 50, { align: 'center' });
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, 50, pageHeight - 30, { align: 'center' });
};

const generateQuotationPDF = (quotation, items, customer, salesPerson) => {
  return new Promise((resolve, reject) => {
    try {
      createDir(path.join(uploadDir, 'quotations'));
      const filename = `quotation-${quotation.quotationNumber}-${Date.now()}.pdf`;
      const filepath = path.join(uploadDir, 'quotations', filename);

      const doc = new PDFDocument();
      const stream = fs.createWriteStream(filepath);

      doc.pipe(stream);

      getCompanyHeader(doc);
      getDocumentTitle(doc, 'QUOTATION');

      const details = {
        'Quotation #': quotation.quotationNumber,
        'Date': new Date(quotation.createdAt).toLocaleDateString(),
        'Valid Until': quotation.validUntil ? new Date(quotation.validUntil).toLocaleDateString() : 'N/A',
        'Customer': customer.companyName,
        'Contact': customer.contactPerson || 'N/A',
        'Email': customer.email
      };

      if (salesPerson) {
        details['Sales Person'] = `${salesPerson.firstName} ${salesPerson.lastName}`;
      }

      let y = getDocumentDetails(doc, details);

      doc.fontSize(12).font('Helvetica-Bold').text('Quotation Items', 50, y);
      y += 20;

      const columns = ['Product', 'Qty', 'Unit', 'Price', 'Total'];
      const rows = items.map(item => [
        item.product?.name || 'N/A',
        item.quantity.toString(),
        item.unit,
        formatCurrency(item.unitPrice, quotation.currency),
        formatCurrency(item.total, quotation.currency)
      ]);

      y = createTable(doc, columns, rows, y);

      doc.fontSize(10).font('Helvetica-Bold');
      doc.text(`Subtotal: ${formatCurrency(quotation.subtotal, quotation.currency)}`, 50, y);
      y += 15;
      doc.text(`Discount: ${formatCurrency(quotation.discount, quotation.currency)}`, 50, y);
      y += 15;
      doc.text(`Tax (${quotation.taxRate}%): ${formatCurrency(quotation.tax, quotation.currency)}`, 50, y);
      y += 20;
      doc.fontSize(12).text(`TOTAL: ${formatCurrency(quotation.total, quotation.currency)}`, 50, y);

      y += 30;
      if (quotation.terms) {
        doc.fontSize(10).font('Helvetica-Bold').text('Terms & Conditions:', 50, y);
        y += 15;
        doc.font('Helvetica').fontSize(9).text(quotation.terms, 50, y, { width: 500 });
      }

      addFooter(doc);

      doc.end();

      stream.on('finish', () => resolve(filename));
      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
};

const generateProformaInvoicePDF = (pi, items, customer) => {
  return new Promise((resolve, reject) => {
    try {
      createDir(path.join(uploadDir, 'proforma_invoices'));
      const filename = `pi-${pi.piNumber}-${Date.now()}.pdf`;
      const filepath = path.join(uploadDir, 'proforma_invoices', filename);

      const doc = new PDFDocument();
      const stream = fs.createWriteStream(filepath);

      doc.pipe(stream);

      getCompanyHeader(doc);
      getDocumentTitle(doc, 'PROFORMA INVOICE');

      const details = {
        'PI #': pi.piNumber,
        'Date': new Date(pi.createdAt).toLocaleDateString(),
        'Valid Until': pi.validUntil ? new Date(pi.validUntil).toLocaleDateString() : 'N/A',
        'Customer': customer.companyName,
        'Contact': customer.contactPerson || 'N/A',
        'Email': customer.email,
        'Payment Terms': pi.paymentTerms
      };

      let y = getDocumentDetails(doc, details);

      doc.fontSize(12).font('Helvetica-Bold').text('Items', 50, y);
      y += 20;

      const columns = ['Product', 'Qty', 'Unit', 'Price', 'Total'];
      const rows = items.map(item => [
        item.product?.name || 'N/A',
        item.quantity.toString(),
        item.unit,
        formatCurrency(item.unitPrice, pi.currency),
        formatCurrency(item.total, pi.currency)
      ]);

      y = createTable(doc, columns, rows, y);

      doc.fontSize(10).font('Helvetica-Bold');
      doc.text(`Subtotal: ${formatCurrency(pi.subtotal, pi.currency)}`, 50, y);
      y += 15;
      doc.text(`Discount: ${formatCurrency(pi.discount, pi.currency)}`, 50, y);
      y += 15;
      doc.text(`Tax: ${formatCurrency(pi.tax, pi.currency)}`, 50, y);
      y += 20;
      doc.fontSize(12).text(`TOTAL: ${formatCurrency(pi.total, pi.currency)}`, 50, y);

      y += 30;
      doc.fontSize(10).font('Helvetica-Bold').text('Bank Details:', 50, y);
      y += 15;
      doc.font('Helvetica').fontSize(9);
      if (pi.bankDetails && Object.keys(pi.bankDetails).length > 0) {
        Object.entries(pi.bankDetails).forEach(([key, value]) => {
          doc.text(`${key}: ${value}`, 50, y);
          y += 12;
        });
      }

      addFooter(doc);

      doc.end();

      stream.on('finish', () => resolve(filename));
      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
};

const generateSalesOrderPDF = (salesOrder, items, customer, factory) => {
  return new Promise((resolve, reject) => {
    try {
      createDir(path.join(uploadDir, 'sales_orders'));
      const filename = `so-${salesOrder.orderNumber}-${Date.now()}.pdf`;
      const filepath = path.join(uploadDir, 'sales_orders', filename);

      const doc = new PDFDocument();
      const stream = fs.createWriteStream(filepath);

      doc.pipe(stream);

      getCompanyHeader(doc);
      getDocumentTitle(doc, 'SALES ORDER');

      const details = {
        'Order #': salesOrder.orderNumber,
        'Date': new Date(salesOrder.createdAt).toLocaleDateString(),
        'Status': salesOrder.status,
        'Customer': customer.companyName,
        'Factory': factory.companyName,
        'Delivery': salesOrder.estimatedDelivery ? new Date(salesOrder.estimatedDelivery).toLocaleDateString() : 'N/A'
      };

      let y = getDocumentDetails(doc, details);

      doc.fontSize(12).font('Helvetica-Bold').text('Order Items', 50, y);
      y += 20;

      const columns = ['Product', 'Qty', 'Unit', 'Price', 'Total'];
      const rows = items.map(item => [
        item.product?.name || 'N/A',
        item.quantity.toString(),
        item.unit,
        formatCurrency(item.unitPrice, salesOrder.currency),
        formatCurrency(item.total, salesOrder.currency)
      ]);

      y = createTable(doc, columns, rows, y);

      doc.fontSize(10).font('Helvetica-Bold');
      doc.text(`Subtotal: ${formatCurrency(salesOrder.subtotal, salesOrder.currency)}`, 50, y);
      y += 15;
      doc.text(`Discount: ${formatCurrency(salesOrder.discount, salesOrder.currency)}`, 50, y);
      y += 15;
      doc.text(`Tax: ${formatCurrency(salesOrder.tax, salesOrder.currency)}`, 50, y);
      y += 20;
      doc.fontSize(12).text(`TOTAL: ${formatCurrency(salesOrder.total, salesOrder.currency)}`, 50, y);

      addFooter(doc);

      doc.end();

      stream.on('finish', () => resolve(filename));
      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
};

const generatePurchaseOrderPDF = (purchaseOrder, items, factory) => {
  return new Promise((resolve, reject) => {
    try {
      createDir(path.join(uploadDir, 'purchase_orders'));
      const filename = `po-${purchaseOrder.poNumber}-${Date.now()}.pdf`;
      const filepath = path.join(uploadDir, 'purchase_orders', filename);

      const doc = new PDFDocument();
      const stream = fs.createWriteStream(filepath);

      doc.pipe(stream);

      getCompanyHeader(doc);
      getDocumentTitle(doc, 'PURCHASE ORDER');

      const details = {
        'PO #': purchaseOrder.poNumber,
        'Date': new Date(purchaseOrder.createdAt).toLocaleDateString(),
        'Status': purchaseOrder.status,
        'Factory': factory.companyName,
        'Contact': factory.contactPerson || 'N/A',
        'Expected Delivery': purchaseOrder.expectedDelivery ? new Date(purchaseOrder.expectedDelivery).toLocaleDateString() : 'N/A'
      };

      let y = getDocumentDetails(doc, details);

      doc.fontSize(12).font('Helvetica-Bold').text('PO Items', 50, y);
      y += 20;

      const columns = ['Product', 'Qty', 'Unit', 'Price', 'Total'];
      const rows = items.map(item => [
        item.product?.name || 'N/A',
        item.quantity.toString(),
        item.unit,
        formatCurrency(item.unitPrice, purchaseOrder.currency),
        formatCurrency(item.total, purchaseOrder.currency)
      ]);

      y = createTable(doc, columns, rows, y);

      doc.fontSize(10).font('Helvetica-Bold');
      doc.text(`Subtotal: ${formatCurrency(purchaseOrder.subtotal, purchaseOrder.currency)}`, 50, y);
      y += 15;
      doc.fontSize(12).text(`TOTAL: ${formatCurrency(purchaseOrder.total, purchaseOrder.currency)}`, 50, y);

      addFooter(doc);

      doc.end();

      stream.on('finish', () => resolve(filename));
      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
};

const generatePackingListPDF = (packingList, items) => {
  return new Promise((resolve, reject) => {
    try {
      createDir(path.join(uploadDir, 'packing_lists'));
      const filename = `pl-${packingList.packingListNumber}-${Date.now()}.pdf`;
      const filepath = path.join(uploadDir, 'packing_lists', filename);

      const doc = new PDFDocument();
      const stream = fs.createWriteStream(filepath);

      doc.pipe(stream);

      getCompanyHeader(doc);
      getDocumentTitle(doc, 'PACKING LIST');

      const details = {
        'PL #': packingList.packingListNumber,
        'Date': new Date(packingList.createdAt).toLocaleDateString(),
        'Total Packages': packingList.totalPackages,
        'Gross Weight': `${packingList.totalGrossWeight} kg`,
        'Net Weight': `${packingList.totalNetWeight} kg`,
        'Volume': `${packingList.totalVolume} cbm`
      };

      let y = getDocumentDetails(doc, details);

      doc.fontSize(12).font('Helvetica-Bold').text('Items', 50, y);
      y += 20;

      const columns = ['Product', 'Qty', 'Unit', 'Package #', 'Weight'];
      const rows = items.map(item => [
        item.product?.name || 'N/A',
        item.quantity.toString(),
        item.unit,
        item.packageNumber || 'N/A',
        `${item.grossWeight || 0} kg`
      ]);

      y = createTable(doc, columns, rows, y);

      addFooter(doc);

      doc.end();

      stream.on('finish', () => resolve(filename));
      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
};

const generateInvoicePDF = (invoice, salesOrder, customer) => {
  return new Promise((resolve, reject) => {
    try {
      createDir(path.join(uploadDir, 'invoices'));
      const filename = `inv-${invoice.invoiceNumber}-${Date.now()}.pdf`;
      const filepath = path.join(uploadDir, 'invoices', filename);

      const doc = new PDFDocument();
      const stream = fs.createWriteStream(filepath);

      doc.pipe(stream);

      getCompanyHeader(doc);
      getDocumentTitle(doc, 'INVOICE');

      const details = {
        'Invoice #': invoice.invoiceNumber,
        'Date': new Date(invoice.createdAt).toLocaleDateString(),
        'Due Date': invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString() : 'N/A',
        'Customer': customer.companyName,
        'Contact': customer.contactPerson || 'N/A',
        'Email': customer.email,
        'Status': invoice.status
      };

      let y = getDocumentDetails(doc, details);

      doc.fontSize(12).font('Helvetica-Bold').text('Invoice Details', 50, y);
      y += 20;

      const columns = ['Description', 'Amount', 'Currency'];
      const rows = [
        ['Subtotal', invoice.subtotal.toString(), invoice.currency],
        ['Discount', `-${invoice.discount}`, invoice.currency],
        ['Tax', invoice.tax.toString(), invoice.currency]
      ];

      y = createTable(doc, columns, rows, y);

      doc.fontSize(10).font('Helvetica-Bold');
      doc.text(`TOTAL: ${formatCurrency(invoice.total, invoice.currency)}`, 50, y);
      y += 20;
      doc.text(`Paid Amount: ${formatCurrency(invoice.paidAmount, invoice.currency)}`, 50, y);
      y += 15;
      doc.text(`Balance: ${formatCurrency(invoice.balance, invoice.currency)}`, 50, y);

      y += 30;
      doc.fontSize(10).font('Helvetica-Bold').text('Payment Terms:', 50, y);
      y += 15;
      doc.font('Helvetica').fontSize(9).text(invoice.paymentTerms || 'N/A', 50, y);

      y += 30;
      doc.fontSize(10).font('Helvetica-Bold').text('Bank Details:', 50, y);
      y += 15;
      doc.font('Helvetica').fontSize(9);
      doc.text('Please contact accounting for bank transfer details', 50, y);

      addFooter(doc);

      doc.end();

      stream.on('finish', () => resolve(filename));
      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
};

const generateInspectionCertificatePDF = (inspection, report, factory) => {
  return new Promise((resolve, reject) => {
    try {
      createDir(path.join(uploadDir, 'inspection_certificates'));
      const filename = `cert-${inspection.inspectionNumber}-${Date.now()}.pdf`;
      const filepath = path.join(uploadDir, 'inspection_certificates', filename);

      const doc = new PDFDocument();
      const stream = fs.createWriteStream(filepath);

      doc.pipe(stream);

      getCompanyHeader(doc);
      getDocumentTitle(doc, 'INSPECTION CERTIFICATE');

      const details = {
        'Certificate #': inspection.inspectionNumber,
        'Date': new Date(inspection.completedDate || inspection.createdAt).toLocaleDateString(),
        'Factory': factory.companyName,
        'Type': inspection.type,
        'Result': inspection.overallResult || 'Pending'
      };

      let y = getDocumentDetails(doc, details);

      doc.fontSize(12).font('Helvetica-Bold').text('Inspection Findings', 50, y);
      y += 20;

      if (report) {
        doc.fontSize(10).font('Helvetica');
        doc.text(`Overall Result: ${report.overallResult}`, 50, y);
        y += 15;
        doc.text(`Findings: ${report.findings || 'No findings'}`, 50, y, { width: 500 });
        y += 60;
        doc.text(`Recommendations: ${report.recommendations || 'None'}`, 50, y, { width: 500 });
      } else {
        doc.fontSize(10).font('Helvetica');
        doc.text('Inspection report pending completion', 50, y);
      }

      y += 60;
      doc.fontSize(9).font('Helvetica-Bold').text('This certifies that the inspection was conducted according to trading standards.', 50, y);

      addFooter(doc);

      doc.end();

      stream.on('finish', () => resolve(filename));
      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
};

const generateShipmentDocumentPDF = (shipment, salesOrder, customer) => {
  return new Promise((resolve, reject) => {
    try {
      createDir(path.join(uploadDir, 'shipment_documents'));
      const filename = `shp-${shipment.shipmentNumber}-${Date.now()}.pdf`;
      const filepath = path.join(uploadDir, 'shipment_documents', filename);

      const doc = new PDFDocument();
      const stream = fs.createWriteStream(filepath);

      doc.pipe(stream);

      getCompanyHeader(doc);
      getDocumentTitle(doc, 'SHIPMENT DOCUMENT');

      const details = {
        'Shipment #': shipment.shipmentNumber,
        'Date': new Date(shipment.createdAt).toLocaleDateString(),
        'Customer': customer.companyName,
        'Order': salesOrder.orderNumber,
        'Status': shipment.status
      };

      let y = getDocumentDetails(doc, details);

      doc.fontSize(12).font('Helvetica-Bold').text('Shipping Details', 50, y);
      y += 20;

      const columns = ['Detail', 'Value'];
      const rows = [
        ['Carrier', shipment.carrier || 'N/A'],
        ['Vessel Name', shipment.vesselName || 'N/A'],
        ['Container Number', shipment.containerNumber || 'N/A'],
        ['Container Type', shipment.containerType || 'N/A'],
        ['Port of Loading', shipment.portOfLoading || 'N/A'],
        ['Port of Discharge', shipment.portOfDischarge || 'N/A'],
        ['ETA', shipment.eta ? new Date(shipment.eta).toLocaleDateString() : 'N/A']
      ];

      y = createTable(doc, columns, rows, y);

      y += 20;
      doc.fontSize(10).font('Helvetica-Bold').text('Tracking Number:', 50, y);
      y += 15;
      doc.font('Helvetica').fontSize(12).text(shipment.containerNumber || 'N/A', 50, y);

      addFooter(doc);

      doc.end();

      stream.on('finish', () => resolve(filename));
      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
};

const generateCreditNotePDF = (creditNote, customer) => {
  return new Promise((resolve, reject) => {
    try {
      createDir(path.join(uploadDir, 'credit_notes'));
      const filename = `cn-${creditNote.invoiceNumber || creditNote.id}-${Date.now()}.pdf`;
      const filepath = path.join(uploadDir, 'credit_notes', filename);

      const doc = new PDFDocument();
      const stream = fs.createWriteStream(filepath);

      doc.pipe(stream);

      getCompanyHeader(doc);
      getDocumentTitle(doc, 'CREDIT NOTE');

      const details = {
        'Credit Note #': creditNote.invoiceNumber || creditNote.id,
        'Date': new Date(creditNote.createdAt).toLocaleDateString(),
        'Customer': customer.companyName,
        'Contact': customer.contactPerson || 'N/A',
        'Email': customer.email
      };

      let y = getDocumentDetails(doc, details);

      doc.fontSize(12).font('Helvetica-Bold').text('Credit Details', 50, y);
      y += 20;

      const columns = ['Description', 'Amount', 'Currency'];
      const rows = [
        ['Subtotal', creditNote.subtotal?.toString() || '0', creditNote.currency || 'USD'],
        ['Tax Adjustment', (creditNote.tax || 0).toString(), creditNote.currency || 'USD']
      ];

      y = createTable(doc, columns, rows, y);

      doc.fontSize(10).font('Helvetica-Bold');
      doc.text(`Credit Amount: ${formatCurrency(creditNote.total || 0, creditNote.currency || 'USD')}`, 50, y);

      y += 30;
      doc.font('Helvetica').fontSize(9);
      doc.text(creditNote.notes || 'Credit note for adjustment', 50, y, { width: 500 });

      addFooter(doc);

      doc.end();

      stream.on('finish', () => resolve(filename));
      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
};

const generateStatementOfAccountPDF = (customer, invoices, payments) => {
  return new Promise((resolve, reject) => {
    try {
      createDir(path.join(uploadDir, 'statements'));
      const filename = `stmt-${customer.id}-${Date.now()}.pdf`;
      const filepath = path.join(uploadDir, 'statements', filename);

      const doc = new PDFDocument();
      const stream = fs.createWriteStream(filepath);

      doc.pipe(stream);

      getCompanyHeader(doc);
      getDocumentTitle(doc, 'STATEMENT OF ACCOUNT');

      const details = {
        'Customer': customer.companyName,
        'Contact': customer.contactPerson || 'N/A',
        'Email': customer.email,
        'Statement Date': new Date().toLocaleDateString()
      };

      let y = getDocumentDetails(doc, details);

      doc.fontSize(12).font('Helvetica-Bold').text('Account Summary', 50, y);
      y += 20;

      const totalInvoices = invoices.reduce((sum, inv) => sum + parseFloat(inv.total || 0), 0);
      const totalPaid = payments.reduce((sum, pay) => sum + parseFloat(pay.amount || 0), 0);
      const balance = totalInvoices - totalPaid;

      const columns = ['Metric', 'Amount'];
      const rows = [
        ['Total Invoices', formatCurrency(totalInvoices, customer.currency || 'USD')],
        ['Total Paid', formatCurrency(totalPaid, customer.currency || 'USD')],
        ['Outstanding Balance', formatCurrency(balance, customer.currency || 'USD')]
      ];

      y = createTable(doc, columns, rows, y);

      y += 30;
      doc.fontSize(12).font('Helvetica-Bold').text('Recent Invoices', 50, y);
      y += 20;

      const invColumns = ['Invoice #', 'Date', 'Amount', 'Status'];
      const invRows = invoices.slice(0, 5).map(inv => [
        inv.invoiceNumber,
        new Date(inv.createdAt).toLocaleDateString(),
        formatCurrency(inv.total, inv.currency || 'USD'),
        inv.status
      ]);

      y = createTable(doc, invColumns, invRows, y);

      addFooter(doc);

      doc.end();

      stream.on('finish', () => resolve(filename));
      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
};

// ─────────────────────────────────────────────────────────────────────────────
// SALES NOTE  (Purchase Contract — signed ProformaInvoice)
// Arguments:
//   pi        — ProformaInvoice record (piNumber, createdAt, currency,
//               paymentTerms, incoterm, portOfLoading, portOfDischarge,
//               deliveryDate, subtotal, discount, tax, total, bankDetails,
//               notes)
//   items     — array of ProformaInvoiceItem { product, quantity, unit,
//               unitPrice, total, hsCode }
//   customer  — Customer { companyName, contactPerson, address, city, country,
//               email, phone }
//   signedBy  — optional { name, title, date } for seller signature block
// ─────────────────────────────────────────────────────────────────────────────
const generateSalesNotePDF = (pi, items, customer, signedBy = {}) => {
  return new Promise((resolve, reject) => {
    try {
      createDir(path.join(uploadDir, 'sales_notes'));
      const filename = `sales-note-${pi.piNumber}-${Date.now()}.pdf`;
      const filepath = path.join(uploadDir, 'sales_notes', filename);

      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const stream = fs.createWriteStream(filepath);
      doc.pipe(stream);

      // ── Header ──────────────────────────────────────────────────────────────
      doc.fontSize(16).font('Helvetica-Bold')
         .text(process.env.PDF_COMPANY_NAME || 'Sovern House', 50, 30);
      doc.fontSize(9).font('Helvetica')
         .text(process.env.PDF_COMPANY_ADDRESS || '', 50, 50)
         .text(`Tel: ${process.env.PDF_COMPANY_PHONE || ''}`, 50, 63)
         .text(`Email: ${process.env.PDF_COMPANY_EMAIL || ''}`, 50, 76);

      // Document title + number (right-aligned)
      doc.fontSize(18).font('Helvetica-Bold')
         .text('SALES NOTE', 300, 30, { align: 'right', width: 245 });
      doc.fontSize(10).font('Helvetica')
         .text(`Contract Ref: ${pi.piNumber}`, 300, 56, { align: 'right', width: 245 })
         .text(`Date: ${new Date(pi.createdAt || Date.now()).toLocaleDateString('en-GB')}`, 300, 70, { align: 'right', width: 245 });

      doc.moveTo(50, 100).lineTo(545, 100).stroke();

      // ── Parties ─────────────────────────────────────────────────────────────
      let y = 115;
      doc.fontSize(9).font('Helvetica-Bold').text('SELLER', 50, y);
      doc.text('BUYER', 300, y);

      y += 12;
      doc.font('Helvetica').fontSize(9)
         .text(process.env.PDF_COMPANY_NAME || 'Sovern House', 50, y)
         .text(customer.companyName || '', 300, y);

      y += 12;
      if (process.env.PDF_COMPANY_ADDRESS) {
        doc.text(process.env.PDF_COMPANY_ADDRESS, 50, y);
      }
      const buyerAddr = [customer.address, customer.city, customer.country].filter(Boolean).join(', ');
      doc.text(buyerAddr, 300, y);

      y += 12;
      doc.text(`Email: ${process.env.PDF_COMPANY_EMAIL || ''}`, 50, y)
         .text(`Contact: ${customer.contactPerson || ''}`, 300, y);

      y += 12;
      doc.text(`Tel: ${process.env.PDF_COMPANY_PHONE || ''}`, 50, y)
         .text(`Email: ${customer.email || ''}`, 300, y);

      y += 20;
      doc.moveTo(50, y).lineTo(545, y).stroke();
      y += 12;

      // ── Trade Terms ─────────────────────────────────────────────────────────
      doc.fontSize(9).font('Helvetica-Bold').text('TRADE TERMS', 50, y);
      y += 12;
      doc.font('Helvetica').fontSize(9);
      const tradeTerms = [
        ['Incoterm',        pi.incoterm || 'FOB'],
        ['Port of Loading',  pi.portOfLoading || '—'],
        ['Port of Discharge',pi.portOfDischarge || '—'],
        ['Payment Terms',   pi.paymentTerms || '—'],
        ['Estimated Delivery', pi.deliveryDate
          ? new Date(pi.deliveryDate).toLocaleDateString('en-GB') : '—'],
        ['Currency',        pi.currency || 'USD'],
      ];
      tradeTerms.forEach(([label, val]) => {
        doc.font('Helvetica-Bold').text(`${label}: `, 50, y, { continued: true })
           .font('Helvetica').text(val);
        y += 14;
      });

      y += 6;
      doc.moveTo(50, y).lineTo(545, y).stroke();
      y += 12;

      // ── Line Items ──────────────────────────────────────────────────────────
      doc.fontSize(9).font('Helvetica-Bold').text('ORDER DETAILS', 50, y);
      y += 12;

      // Table header
      const colX = [50, 210, 300, 355, 400, 475];
      const colW = [155, 85, 50, 40, 70, 65];
      const headers = ['Product / Description', 'SKU', 'Qty', 'Unit', 'Unit Price', 'Total'];

      doc.rect(50, y, 495, 16).fillAndStroke('#f0f0f0', '#000');
      doc.fillColor('black').fontSize(8).font('Helvetica-Bold');
      headers.forEach((h, i) => {
        doc.text(h, colX[i] + 2, y + 3, { width: colW[i] - 4 });
      });
      y += 16;

      doc.font('Helvetica').fontSize(8);
      items.forEach((item, idx) => {
        const rowH = 18;
        if (idx % 2 === 0) doc.rect(50, y, 495, rowH).fill('#fafafa').stroke('#ccc');
        else doc.rect(50, y, 495, rowH).fill('#ffffff').stroke('#ccc');
        doc.fillColor('black');

        const productName = item.product?.name || item.description || 'N/A';
        const sku = item.product?.sku || item.sku || '—';
        doc.text(productName, colX[0] + 2, y + 4, { width: colW[0] - 4 });
        doc.text(sku, colX[1] + 2, y + 4, { width: colW[1] - 4 });
        doc.text(String(item.quantity || 0), colX[2] + 2, y + 4, { width: colW[2] - 4 });
        doc.text(item.unit || '—', colX[3] + 2, y + 4, { width: colW[3] - 4 });
        doc.text(formatCurrency(item.unitPrice, pi.currency), colX[4] + 2, y + 4, { width: colW[4] - 4 });
        doc.text(formatCurrency(item.total, pi.currency), colX[5] + 2, y + 4, { width: colW[5] - 4 });
        y += rowH;
      });

      // ── Totals ───────────────────────────────────────────────────────────────
      y += 6;
      const totalsX = 350;
      doc.fontSize(9).font('Helvetica');
      [
        ['Subtotal', formatCurrency(pi.subtotal, pi.currency)],
        ['Discount', formatCurrency(pi.discount || 0, pi.currency)],
        [`Tax`, formatCurrency(pi.tax || 0, pi.currency)],
      ].forEach(([label, val]) => {
        doc.text(label + ':', totalsX, y, { width: 100 })
           .text(val, totalsX + 100, y, { width: 95, align: 'right' });
        y += 14;
      });
      doc.moveTo(totalsX, y).lineTo(545, y).stroke();
      y += 4;
      doc.fontSize(11).font('Helvetica-Bold')
         .text('TOTAL:', totalsX, y, { width: 100 })
         .text(formatCurrency(pi.total, pi.currency), totalsX + 100, y, { width: 95, align: 'right' });
      y += 20;

      // ── Bank Details ─────────────────────────────────────────────────────────
      if (pi.bankDetails && Object.keys(pi.bankDetails).length > 0) {
        doc.moveTo(50, y).lineTo(545, y).stroke();
        y += 10;
        doc.fontSize(9).font('Helvetica-Bold').text('PAYMENT / BANK DETAILS', 50, y);
        y += 12;
        doc.font('Helvetica').fontSize(9);
        Object.entries(pi.bankDetails).forEach(([k, v]) => {
          doc.text(`${k}: ${v}`, 50, y);
          y += 12;
        });
        y += 4;
      }

      // ── Notes ────────────────────────────────────────────────────────────────
      if (pi.notes) {
        doc.moveTo(50, y).lineTo(545, y).stroke();
        y += 10;
        doc.fontSize(9).font('Helvetica-Bold').text('NOTES / SPECIAL INSTRUCTIONS', 50, y);
        y += 12;
        doc.font('Helvetica').fontSize(9).text(pi.notes, 50, y, { width: 495 });
        y += doc.heightOfString(pi.notes, { width: 495 }) + 8;
      }

      // ── Terms boilerplate ────────────────────────────────────────────────────
      doc.moveTo(50, y).lineTo(545, y).stroke();
      y += 10;
      doc.fontSize(8).font('Helvetica-Oblique')
         .text(
           'This Sales Note constitutes the binding purchase contract between Seller and Buyer upon signature by both parties. ' +
           'Delivery shall be made under the Incoterm stated above. Title and risk transfer as per the applicable Incoterm. ' +
           'Disputes shall be resolved by arbitration under ICC rules.',
           50, y, { width: 495 }
         );
      y += 32;

      // ── Signature Blocks ─────────────────────────────────────────────────────
      // Ensure signature blocks fit on page; add page if needed
      if (y > 680) {
        doc.addPage();
        y = 50;
      }

      doc.fontSize(9).font('Helvetica-Bold');
      doc.text('FOR AND ON BEHALF OF SELLER:', 50, y);
      doc.text('FOR AND ON BEHALF OF BUYER:', 300, y);

      y += 40;
      doc.moveTo(50, y).lineTo(220, y).stroke();
      doc.moveTo(300, y).lineTo(470, y).stroke();

      y += 4;
      doc.font('Helvetica').fontSize(9);
      doc.text(signedBy.name || process.env.PDF_COMPANY_NAME || 'Authorised Signatory', 50, y);
      doc.text('Authorised Signatory', 300, y);

      y += 12;
      doc.text(`Title: ${signedBy.title || 'Director'}`, 50, y);
      doc.text('Title: ______________________', 300, y);

      y += 12;
      doc.text(`Date: ${signedBy.date || new Date().toLocaleDateString('en-GB')}`, 50, y);
      doc.text('Date: ______________________', 300, y);

      // ── Footer ───────────────────────────────────────────────────────────────
      addFooter(doc);
      doc.end();

      stream.on('finish', () => resolve(filename));
      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
};

// ─────────────────────────────────────────────────────────────────────────────
// PRODUCT SPEC SHEET  (per-SKU datasheet for sales & marketing)
// Arguments:
//   product      — Product record { name, sku, description, specifications,
//                  unit, minOrderQty, weight, hsCode }
//   category     — ProductCategory { name }
//   factory      — Factory { companyName, city, country, certifications }
//   price        — ProductPrice { sellingPrice, currency } (optional)
// ─────────────────────────────────────────────────────────────────────────────
const generateProductSpecSheetPDF = (product, category, factory, price = null) => {
  return new Promise((resolve, reject) => {
    try {
      createDir(path.join(uploadDir, 'spec_sheets'));
      const filename = `spec-sheet-${product.sku}-${Date.now()}.pdf`;
      const filepath = path.join(uploadDir, 'spec_sheets', filename);

      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const stream = fs.createWriteStream(filepath);
      doc.pipe(stream);

      // ── Header bar ───────────────────────────────────────────────────────────
      doc.rect(0, 0, 595, 80).fill('#1a1a2e');
      doc.fillColor('white');
      doc.fontSize(20).font('Helvetica-Bold')
         .text(process.env.PDF_COMPANY_NAME || 'Sovern House', 50, 18);
      doc.fontSize(9).font('Helvetica')
         .text('PRODUCT SPECIFICATION SHEET', 50, 44)
         .text(`Generated: ${new Date().toLocaleDateString('en-GB')}`, 50, 56);

      // Category label (right side of header)
      doc.fontSize(11).font('Helvetica-Bold')
         .text(category?.name || 'Product', 300, 28, { align: 'right', width: 245 });

      doc.fillColor('black');

      // ── Product name + SKU ───────────────────────────────────────────────────
      let y = 100;
      doc.fontSize(16).font('Helvetica-Bold')
         .text(product.name || 'Product Name', 50, y);
      y += 22;
      doc.fontSize(10).font('Helvetica')
         .text(`SKU: ${product.sku}`, 50, y);

      if (price) {
        doc.text(`Price: ${formatCurrency(price.sellingPrice, price.currency)} / ${product.unit || 'unit'}`,
          300, y, { align: 'right', width: 245 });
      }

      y += 18;
      doc.moveTo(50, y).lineTo(545, y).stroke();
      y += 12;

      // ── Description ──────────────────────────────────────────────────────────
      doc.fontSize(9).font('Helvetica-Bold').text('PRODUCT DESCRIPTION', 50, y);
      y += 12;
      doc.font('Helvetica').fontSize(9)
         .text(product.description || '—', 50, y, { width: 495 });
      y += doc.heightOfString(product.description || '—', { width: 495 }) + 14;

      // ── Technical Specifications ─────────────────────────────────────────────
      doc.moveTo(50, y).lineTo(545, y).stroke();
      y += 10;
      doc.fontSize(9).font('Helvetica-Bold').text('TECHNICAL SPECIFICATIONS', 50, y);
      y += 12;

      let specs = {};
      if (product.specifications) {
        if (typeof product.specifications === 'string') {
          try { specs = JSON.parse(product.specifications); } catch (e) { specs = {}; }
        } else {
          specs = product.specifications;
        }
      }

      if (Object.keys(specs).length > 0) {
        doc.font('Helvetica').fontSize(9);
        const specEntries = Object.entries(specs);
        // Two-column layout
        const half = Math.ceil(specEntries.length / 2);
        const leftCol = specEntries.slice(0, half);
        const rightCol = specEntries.slice(half);
        const maxRows = Math.max(leftCol.length, rightCol.length);

        for (let i = 0; i < maxRows; i++) {
          if (leftCol[i]) {
            const [k, v] = leftCol[i];
            const label = k.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase());
            doc.font('Helvetica-Bold').text(`${label}: `, 50, y, { continued: true, width: 220 })
               .font('Helvetica').text(String(v));
          }
          if (rightCol[i]) {
            const [k, v] = rightCol[i];
            const label = k.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase());
            doc.font('Helvetica-Bold').text(`${label}: `, 300, y, { continued: true, width: 220 })
               .font('Helvetica').text(String(v));
          }
          y += 14;
        }
      } else {
        doc.font('Helvetica').fontSize(9).text('No specifications available.', 50, y);
        y += 14;
      }

      y += 6;
      doc.moveTo(50, y).lineTo(545, y).stroke();
      y += 10;

      // ── Commercial Details ───────────────────────────────────────────────────
      doc.fontSize(9).font('Helvetica-Bold').text('COMMERCIAL DETAILS', 50, y);
      y += 12;
      doc.font('Helvetica').fontSize(9);
      const commercialRows = [
        ['Unit of Measure', product.unit || '—'],
        ['Minimum Order Qty', product.minOrderQty ? `${product.minOrderQty} ${product.unit || 'units'}` : '—'],
        ['Gross Weight (per unit)', product.weight ? `${product.weight} kg` : '—'],
        ['HS Code', product.hsCode || 'TBC — consult licensed customs broker'],
        ['Country of Origin', factory?.country || 'China'],
        ['Factory / Supplier', factory?.companyName || '—'],
        ['Lead Time', factory?.leadTimeDays ? `${factory.leadTimeDays} days` : '—'],
      ];
      commercialRows.forEach(([label, val]) => {
        doc.font('Helvetica-Bold').text(`${label}: `, 50, y, { continued: true, width: 220 })
           .font('Helvetica').text(val);
        y += 14;
      });

      // ── Certifications ───────────────────────────────────────────────────────
      if (factory?.certifications && factory.certifications.length > 0) {
        y += 6;
        doc.moveTo(50, y).lineTo(545, y).stroke();
        y += 10;
        doc.fontSize(9).font('Helvetica-Bold').text('FACTORY CERTIFICATIONS', 50, y);
        y += 12;
        const certs = Array.isArray(factory.certifications)
          ? factory.certifications
          : (typeof factory.certifications === 'string' ? JSON.parse(factory.certifications) : []);
        doc.font('Helvetica').fontSize(9)
           .text(certs.join(' · '), 50, y, { width: 495 });
        y += 14;
      }

      // ── Compliance note ──────────────────────────────────────────────────────
      y += 8;
      doc.moveTo(50, y).lineTo(545, y).stroke();
      y += 10;
      doc.fontSize(8).font('Helvetica-Oblique')
         .text(
           'IMPORTANT: HS codes must be verified with a licensed customs broker before import. ' +
           'Pricing and specifications are indicative and subject to final order confirmation. ' +
           'This document is for reference only and does not constitute a binding offer.',
           50, y, { width: 495 }
         );

      addFooter(doc);
      doc.end();

      stream.on('finish', () => resolve(filename));
      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = {
  generateQuotationPDF,
  generateProformaInvoicePDF,
  generateSalesOrderPDF,
  generatePurchaseOrderPDF,
  generatePackingListPDF,
  generateInvoicePDF,
  generateInspectionCertificatePDF,
  generateShipmentDocumentPDF,
  generateCreditNotePDF,
  generateStatementOfAccountPDF,
  generateSalesNotePDF,
  generateProductSpecSheetPDF
};
