/**
 * Phase 4.28f — IronLite Core per-origin price fix (2026-05-19 incident).
 *
 * On 2026-05-19 the FW (Malaysia) and HH (China) IronLite Core price
 * lists were found to carry every line inflated by exactly 7%. Root
 * cause was the AI system prompt instructing "Sovern FOB = Factory FOB /
 * (1 - 0.05)" applied as a markup on top of supplier buyer-ready prices
 * (which already include Alex's commission per the HanHua Sales Rep
 * Agreement). Both lists were generated by reading the FlorWay HanHua
 * Excel correctly, then multiplying every line by 1.07.
 *
 * Two corrupted shapes need fixing in this migration:
 *
 *   (a) Product.originVariants on the 9 IL-180x1220-*.0mm rows was
 *       stored as [{origin, factoryId}] instead of the canonical
 *       Phase 4.9 C-1 shape [{originCountry, fobPriceUsd, priceUnit,
 *       factoryId}]. The Quotation builder reads originCountry +
 *       fobPriceUsd, so this row shape is silently unqueryable today.
 *
 *   (b) Both IronLite Core PriceLists carry sellingPrice values inflated
 *       by 7%. Archive them (isActive=false) so they fall out of every
 *       UI list and any AI fetch. Alex will rebuild from the corrected
 *       originVariants in the next pass.
 *
 * Canonical per-origin prices (from the FlorWay HanHua sales sheet,
 * "USD/M² FOB CHINA" + "USD/M² FOB MALAYSIA" columns, sheet dated
 * UNTIL MAY 15, 2026):
 *
 *   SKU                    | China (HH) | Malaysia (FW)
 *   IL-180x1220-6.5mm      |    9.095   |    9.741
 *   IL-180x1220-7.0mm      |    9.634   |   10.280
 *   IL-180x1220-7.5mm      |   10.161   |   10.807
 *   IL-180x1220-8.0mm      |   10.699   |   11.345
 *   IL-180x1220-8.5mm      |   11.238   |   11.883
 *   IL-180x1220-9.0mm      |   11.765   |   12.411
 *   IL-180x1220-10.0mm     |   12.841   |   13.486
 *   IL-180x1220-11.0mm     |   13.910   |   14.553
 *   IL-180x1220-12.0mm     |   14.980   |   15.629
 *
 * Idempotent via AuditLog sentinel
 * `phase4_28f_ironlite_per_origin_prices_fixed`.
 */

const logger = require('../utils/logger');

const SENTINEL_ACTION = 'phase4_28f_ironlite_per_origin_prices_fixed';

// USD/m². Buyer-ready FOB, inclusive of Alex's commission.
const IRONLITE_PRICES = {
  'IL-180x1220-6.5mm':  { CN: 9.095,  MY: 9.741 },
  'IL-180x1220-7.0mm':  { CN: 9.634,  MY: 10.280 },
  'IL-180x1220-7.5mm':  { CN: 10.161, MY: 10.807 },
  'IL-180x1220-8.0mm':  { CN: 10.699, MY: 11.345 },
  'IL-180x1220-8.5mm':  { CN: 11.238, MY: 11.883 },
  'IL-180x1220-9.0mm':  { CN: 11.765, MY: 12.411 },
  'IL-180x1220-10.0mm': { CN: 12.841, MY: 13.486 },
  'IL-180x1220-11.0mm': { CN: 13.910, MY: 14.553 },
  'IL-180x1220-12.0mm': { CN: 14.980, MY: 15.629 },
};

// The two price-list rows the AI populated with the inflated values on
// 2026-05-17 and 2026-05-19. Archived (isActive=false) so Alex can
// rebuild fresh from the corrected originVariants.
const BAD_PRICE_LIST_IDS = [
  '6eeab3ac-5569-40bd-9646-1b98f9123215', // Engineered SPC - IronLite Core - Malaysia (FW)
  'd6669253-55da-405e-8c83-40fd066a615c', // Engineered SPC - IronLite Core - China (HH)
];

async function hasSentinel(db) {
  if (!db.AuditLog) return false;
  const row = await db.AuditLog.findOne({ where: { action: SENTINEL_ACTION, entity: 'System' } });
  return !!row;
}

async function writeSentinel(db, changes) {
  if (!db.AuditLog) return;
  await db.AuditLog.create({
    userId: null,
    action: SENTINEL_ACTION,
    entity: 'System',
    entityId: '00000000-0000-0000-0000-000000000000',
    changes,
    ipAddress: null,
  });
}

async function migrate428fIronlitePricesFix(db) {
  if (!db.Product || !db.PriceList) {
    logger.info('[4.28f] Product or PriceList model missing; skipping');
    return { skipped: true };
  }
  if (await hasSentinel(db)) {
    return { skipped: true };
  }

  // 1) Normalize originVariants + set per-origin prices on the 9 IL- SKUs.
  let productsFixed = 0;
  const productSummary = [];
  for (const [sku, prices] of Object.entries(IRONLITE_PRICES)) {
    const p = await db.Product.findOne({ where: { sku } });
    if (!p) {
      productSummary.push({ sku, status: 'product_not_found' });
      continue;
    }
    // Preserve factoryId from whatever shape is currently stored. Both
    // {origin} and {originCountry} shapes carry factoryId for the two
    // production lines.
    const existing = Array.isArray(p.originVariants) ? p.originVariants : [];
    const factoryIdByOrigin = {};
    for (const v of existing) {
      const o = String(v.origin || v.originCountry || '').toLowerCase();
      if (o === 'china' || o === 'cn') factoryIdByOrigin.CN = v.factoryId || factoryIdByOrigin.CN;
      if (o === 'malaysia' || o === 'my') factoryIdByOrigin.MY = v.factoryId || factoryIdByOrigin.MY;
    }
    const variants = [
      {
        originCountry: 'CN',
        fobPriceUsd: prices.CN,
        priceUnit: 'sqm',
        factoryId: factoryIdByOrigin.CN || null,
      },
      {
        originCountry: 'MY',
        fobPriceUsd: prices.MY,
        priceUnit: 'sqm',
        factoryId: factoryIdByOrigin.MY || null,
      },
    ];
    await p.update({
      originVariants: variants,
      // baseFobPrice stays as a legacy single-value scalar. For these
      // multi-origin SKUs callers should read originVariants. Keep
      // baseFobPrice in sync with the primary origin so any legacy
      // reader sees a buyer-ready number, not the previous +7% value.
      baseFobPrice: p.originCountry === 'MY' ? prices.MY : prices.CN,
    });
    productsFixed++;
    productSummary.push({ sku, productId: p.id, variants });
  }

  // 2) Archive the two corrupted PriceLists. is_active=false hides them
  //    from every UI list + the assistant's list_price_lists default
  //    filter (active-only).
  let listsArchived = 0;
  const listSummary = [];
  for (const id of BAD_PRICE_LIST_IDS) {
    const pl = await db.PriceList.findByPk(id);
    if (!pl) {
      listSummary.push({ id, status: 'not_found' });
      continue;
    }
    if (pl.isActive === false) {
      listSummary.push({ id, name: pl.name, status: 'already_inactive' });
      continue;
    }
    await pl.update({ isActive: false });
    listsArchived++;
    listSummary.push({ id, name: pl.name, status: 'archived' });
  }

  await writeSentinel(db, {
    productsFixed,
    listsArchived,
    runAt: new Date().toISOString(),
    productSummary,
    listSummary,
  });

  logger.info(`[4.28f] IronLite per-origin prices fixed: ${productsFixed} Products + ${listsArchived} PriceLists archived`);
  return { productsFixed, listsArchived };
}

module.exports = { migrate428fIronlitePricesFix, IRONLITE_PRICES, BAD_PRICE_LIST_IDS };
