const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
  const Lead = sequelize.define('Lead', {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    // Phase 4.8 Commit 3a: human-readable per-day identifier
    // (LD-YYYYMMDD-NNN, e.g. LD-20260515-001). Generated by
    // services/leadNumberGenerator on create. Backfilled on existing
    // 112 prod rows by migrateLeadNumberC3a at boot. UNIQUE so the
    // counter cannot collide; nullable until backfill completes so
    // sequelize.sync({ alter: true }) does not break the migration.
    leadNumber: {
      type: DataTypes.STRING(20),
      allowNull: true,
      unique: true,
    },
    companyName: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    contactName: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    email: {
      type: DataTypes.STRING,
      allowNull: false,
      validate: {
        isEmail: true,
      },
    },
    phone: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    source: {
      type: DataTypes.ENUM('website', 'referral', 'trade_show', 'cold_call', 'social_media', 'advertisement', 'other'),
      defaultValue: 'other',
    },
    status: {
      type: DataTypes.ENUM('new', 'contacted', 'qualified', 'proposal', 'negotiation', 'won', 'lost'),
      defaultValue: 'new',
    },
    assignedToId: {
      type: DataTypes.UUID,
      allowNull: true,
      // references removed — handled by Sequelize association
    },
    industry: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    estimatedValue: {
      type: DataTypes.DECIMAL(15, 2),
      allowNull: true,
    },
    currency: {
      type: DataTypes.STRING,
      defaultValue: 'USD',
    },
    probability: {
      type: DataTypes.INTEGER,
      allowNull: true,
      validate: {
        min: 0,
        max: 100,
      },
    },
    expectedCloseDate: {
      type: DataTypes.DATE,
      allowNull: true,
    },
    description: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    address: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    city: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    state: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    country: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    lostReason: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    wonDate: {
      type: DataTypes.DATE,
      allowNull: true,
    },
    lostDate: {
      type: DataTypes.DATE,
      allowNull: true,
    },
    convertedCustomerId: {
      type: DataTypes.UUID,
      allowNull: true,
      // Note: references removed — SQLite FK enforcement causes INSERT failures
      // when Customers table doesn't exist at seed time. The Sequelize association
      // (Lead.belongsTo Customer) handles the relationship at the ORM level.
    },
    tags: {
      type: DataTypes.JSON,
      defaultValue: [],
    },
    // Additional contacts beyond the primary contactName/email fields.
    // Format: [{ name: string, jobTitle?: string, email?: string, phone?: string }]
    // Added via autoMigrateSchema — no manual migration needed.
    additionalContacts: {
      type: DataTypes.JSON,
      defaultValue: [],
    },
    leadType: {
      type: DataTypes.ENUM('inbound', 'outbound_prospect', 'supplier_contact'),
      defaultValue: 'inbound',
    },
    vertical: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    // Array of sub-category slugs from the product taxonomy (e.g. ["spc", "lvt"])
    // Complements the parent-level `vertical` field with precise product interest tagging.
    productInterests: {
      type: DataTypes.JSON,
      defaultValue: [],
    },
    website: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    // Phase 4.13b removed the Phase 1 legacy `sanctionsScreened` boolean.
    // It was kept "for read compatibility" but nothing kept it in sync
    // with screeningStatus, which created the L-044 state-inconsistency
    // (sanctionsScreened=false + lastScreenedAt populated +
    // screeningStatus=cleared all at once on the same row). New code
    // reads screeningStatus exclusively. Migration:
    // backend/services/migrate413bDropSanctionsScreened.js.
    // Phase 4, C18: full sanctions screening enum + hit details. Lead is
    // screened at create time (company name + country) BEFORE the row
    // persists so we can block creation when flagged. Override is the
    // super-admin attestation path.
    screeningStatus: {
      type: DataTypes.ENUM('pending', 'cleared', 'flagged', 'requires_review', 'override'),
      allowNull: false,
      defaultValue: 'pending',
    },
    sanctionsScreenDetails: {
      type: DataTypes.JSON,
      allowNull: true,
      defaultValue: null,
    },
    lastScreenedAt: {
      type: DataTypes.DATE,
      allowNull: true,
    },
    emailVerified: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
    },
    linkedinUrl: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    // Draft cold email generated by /new-clients research runner. Reviewed
    // and edited by Super Admin before being sent via the OutreachEmail flow.
    // Added via autoMigrateSchema — additive only, no manual migration.
    draftEmailSubject: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    draftEmailBody: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    // Who created this lead. Distinct from assignedToId (the responsible owner).
    // FK declared in .associate() per L-034.
    createdById: {
      type: DataTypes.UUID,
      allowNull: true,
    },
    // What surface created this lead. 'ai_research' means the AI Assistant
    // ran /new-clients on behalf of createdById. UI renders 'AI Assistant
    // (on behalf of <name>)' for ai_research; otherwise just the user name.
    createdBySource: {
      type: DataTypes.ENUM('manual', 'ai_research', 'webhook', 'import'),
      defaultValue: 'manual',
    },
    // Followers / additional responsible team members beyond assignedToId
    // (the primary owner). Stored as JSON array of User UUIDs.
    responsibleUserIds: {
      type: DataTypes.JSON,
      defaultValue: [],
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
    },
    // Multi-brand (Phase 1, D-1). Locked at creation; super_admin override
    // requires audit log entry (Commit 3). FK to Brand.code declared in
    // models/index.js per L-034.
    brandCode: {
      type: DataTypes.STRING(8),
      allowNull: false,
      defaultValue: 'SH',
    },
  }, {
    tableName: 'Leads',
    timestamps: true,
  });

  Lead.associate = (models) => {
    Lead.belongsTo(models.User, { foreignKey: 'assignedToId', as: 'assignedTo' });
    Lead.belongsTo(models.User, { foreignKey: 'createdById', as: 'createdBy' });
    Lead.belongsTo(models.Customer, { foreignKey: 'convertedCustomerId', as: 'convertedCustomer' });
    // Inverse of Activity.belongsTo(Lead). Required for getLeadById's
    // include: [{ model: Activity, as: 'activities' }] to resolve.
    if (models.Activity) {
      Lead.hasMany(models.Activity, { foreignKey: 'leadId', as: 'activities' });
    }
  };

  return Lead;
};
